class ApiConstants {
  static String baseUrl = "https://api.themoviedb.org/3/";
  static String apiKey = "434fcadef5103207fecca9176385a533";
  static String movieImageBaseUrl = "http://image.tmdb.org/t/p/w342/";

  // Get Movie posters and backdrops
  // https://api.themoviedb.org/3/movie/616037/images?api_key=434fcadef5103207fecca9176385a533

  // Test Data:

  static String posterUrl =
      "https://m.media-amazon.com/images/M/MV5BN2FjNmEyNWMtYzM0ZS00NjIyLTg5YzYtYThlMGVjNzE1OGViXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX509_.jpg";

  static String backDropUrl =
      "https://artfulwritercom.files.wordpress.com/2021/11/dune.jpg";

  static List<Map<String, dynamic>> castList = [
    {
      "adult": false,
      "gender": 2,
      "id": 1190668,
      "known_for_department": "Acting",
      "name": "Timothée Chalamet",
      "original_name": "Timothée Chalamet",
      "popularity": 61.101,
      "profile_path": "/giE73ickrnQ61qK8iRdOSv9Oj2Z.jpg",
      "cast_id": 13,
      "character": "Paul Atreides",
      "credit_id": "5b4d01bac3a36823d803cd45",
      "order": 0
    },
    {
      "adult": false,
      "gender": 1,
      "id": 933238,
      "known_for_department": "Acting",
      "name": "Rebecca Ferguson",
      "original_name": "Rebecca Ferguson",
      "popularity": 35.563,
      "profile_path": "/6NRlV9oUipeak7r00V6k73Jb7we.jpg",
      "cast_id": 14,
      "character": "Lady Jessica Atreides",
      "credit_id": "5b90742fc3a368222e002f41",
      "order": 1
    },
    {
      "adult": false,
      "gender": 2,
      "id": 25072,
      "known_for_department": "Acting",
      "name": "Oscar Isaac",
      "original_name": "Oscar Isaac",
      "popularity": 52.519,
      "profile_path": "/BMhVPnf8IreAIYpnHNibMcBVUz.jpg",
      "cast_id": 53,
      "character": "Duke Leto Atreides",
      "credit_id": "5c50bc070e0a2612cccedcb3",
      "order": 2
    },
    {
      "adult": false,
      "gender": 2,
      "id": 16851,
      "known_for_department": "Acting",
      "name": "Josh Brolin",
      "original_name": "Josh Brolin",
      "popularity": 27.916,
      "profile_path": "/sX2etBbIkxRaCsATyw5ZpOVMPTD.jpg",
      "cast_id": 73,
      "character": "Gurney Halleck",
      "credit_id": "5c64750d9251412fb4feec3e",
      "order": 3
    },
    {
      "adult": false,
      "gender": 2,
      "id": 1640,
      "known_for_department": "Acting",
      "name": "Stellan Skarsgård",
      "original_name": "Stellan Skarsgård",
      "popularity": 27.567,
      "profile_path": "/x78BtYHElirO7Iw8bL4m8CnzRDc.jpg",
      "cast_id": 31,
      "character": "Baron Vladimir Harkonnen",
      "credit_id": "5c364b61c3a368273c1c5fee",
      "order": 4
    },
    {
      "adult": false,
      "gender": 2,
      "id": 543530,
      "known_for_department": "Acting",
      "name": "Dave Bautista",
      "original_name": "Dave Bautista",
      "popularity": 28.272,
      "profile_path": "/26YLbFdg2M8dTOim3jWJCLfryO1.jpg",
      "cast_id": 30,
      "character": "Beast Rabban Harkonnen",
      "credit_id": "5c342d10c3a36851f8b52ac9",
      "order": 5
    },
    {
      "adult": false,
      "gender": 1,
      "id": 195666,
      "known_for_department": "Acting",
      "name": "Sharon Duncan-Brewster",
      "original_name": "Sharon Duncan-Brewster",
      "popularity": 2.825,
      "profile_path": "/3UCihGvkuWQbdRBzYgVM52IFPeA.jpg",
      "cast_id": 160,
      "character": "Dr. Liet Kynes",
      "credit_id": "5e37991c4ca676001252ea99",
      "order": 6
    },
    {
      "adult": false,
      "gender": 2,
      "id": 196179,
      "known_for_department": "Acting",
      "name": "Stephen McKinley Henderson",
      "original_name": "Stephen McKinley Henderson",
      "popularity": 6.926,
      "profile_path": "/utsApLREJWm13jyCLMkFwPYYU0M.jpg",
      "cast_id": 209,
      "character": "Thufir Hawat",
      "credit_id": "61468a6985c0a20043d24c95",
      "order": 7
    },
    {
      "adult": false,
      "gender": 1,
      "id": 505710,
      "known_for_department": "Acting",
      "name": "Zendaya",
      "original_name": "Zendaya",
      "popularity": 43.541,
      "profile_path": "/69Pm8AsGm0jmCLfal3VuATsXKIT.jpg",
      "cast_id": 54,
      "character": "Chani",
      "credit_id": "5c5241fa0e0a2612ccd0fc9c",
      "order": 8
    },
    {
      "adult": false,
      "gender": 2,
      "id": 1622,
      "known_for_department": "Acting",
      "name": "Chang Chen",
      "original_name": "Chang Chen",
      "popularity": 10.221,
      "profile_path": "/4BOQ5pJXdsArkMHvyVhrV8Ditnr.jpg",
      "cast_id": 103,
      "character": "Dr. Wellington Yueh",
      "credit_id": "5c8e6e129251410ff4a1c158",
      "order": 9
    },
    {
      "adult": false,
      "gender": 1,
      "id": 44079,
      "known_for_department": "Acting",
      "name": "Charlotte Rampling",
      "original_name": "Charlotte Rampling",
      "popularity": 13.894,
      "profile_path": "/8a7bsHpjJ8cFtHRtHpQQzqNBDIi.jpg",
      "cast_id": 36,
      "character": "Reverend Mother Gaius Helen Mohiam",
      "credit_id": "5c3e88ba9251415524ae5623",
      "order": 10
    },
    {
      "adult": false,
      "gender": 2,
      "id": 117642,
      "known_for_department": "Acting",
      "name": "Jason Momoa",
      "original_name": "Jason Momoa",
      "popularity": 59.625,
      "profile_path": "/6dEFBpZH8C8OijsynkSajQT99Pb.jpg",
      "cast_id": 75,
      "character": "Duncan Idaho",
      "credit_id": "5c6610319251412fc6017577",
      "order": 11
    },
    {
      "adult": false,
      "gender": 2,
      "id": 3810,
      "known_for_department": "Acting",
      "name": "Javier Bardem",
      "original_name": "Javier Bardem",
      "popularity": 24.133,
      "profile_path": "/IShnFg6ijWhpbu29dFBd9PtqQg.jpg",
      "cast_id": 55,
      "character": "Stilgar",
      "credit_id": "5c55434c0e0a26567ac66f76",
      "order": 12
    },
    {
      "adult": false,
      "gender": 2,
      "id": 83854,
      "known_for_department": "Acting",
      "name": "David Dastmalchian",
      "original_name": "David Dastmalchian",
      "popularity": 10.398,
      "profile_path": "/sF7yHISn8kuBy7T39gB5dMpObpk.jpg",
      "cast_id": 77,
      "character": "Piter de Vries",
      "credit_id": "5c6c967b0e0a261e069f48b6",
      "order": 13
    },
    {
      "adult": false,
      "gender": 2,
      "id": 205923,
      "known_for_department": "Acting",
      "name": "Babs Olusanmokun",
      "original_name": "Babs Olusanmokun",
      "popularity": 7.986,
      "profile_path": "/4OWjo1DNlWfiv82kNDNJZNoxqt0.jpg",
      "cast_id": 159,
      "character": "Jamis",
      "credit_id": "5e3799110c27100013728d9c",
      "order": 14
    },
    {
      "adult": false,
      "gender": 1,
      "id": 1856875,
      "known_for_department": "Acting",
      "name": "Golda Rosheuvel",
      "original_name": "Golda Rosheuvel",
      "popularity": 4.416,
      "profile_path": "/nlSIvTWzMEzZGljKYgpZxGcsJtv.jpg",
      "cast_id": 198,
      "character": "Shadout Mapes",
      "credit_id": "60621d77d7a70a007430f1df",
      "order": 15
    },
    {
      "adult": false,
      "gender": 2,
      "id": 2974,
      "known_for_department": "Acting",
      "name": "Roger Yuan",
      "original_name": "Roger Yuan",
      "popularity": 6.087,
      "profile_path": "/jHdxbT6n3ToYKw0DVFIUkva86SO.jpg",
      "cast_id": 197,
      "character": "Lieutenant Lanville",
      "credit_id": "604c3692ae28110029cfb466",
      "order": 16
    },
    {
      "adult": false,
      "gender": 2,
      "id": 3185383,
      "known_for_department": "Acting",
      "name": "Benjamin Clémentine",
      "original_name": "Benjamin Clémentine",
      "popularity": 0.6,
      "profile_path": "/johpHbzqrue6XDG63vapfugGbnn.jpg",
      "cast_id": 206,
      "character": "Herald of the Change",
      "credit_id": "61098872dcf875004856d399",
      "order": 17
    },
    {
      "adult": false,
      "gender": 1,
      "id": 261927,
      "known_for_department": "Acting",
      "name": "Souad Faress",
      "original_name": "Souad Faress",
      "popularity": 3.629,
      "profile_path": "/aEGdIch9eRzJcsAGbF7mAZPUiXt.jpg",
      "cast_id": 208,
      "character": "Bene Gesserit Sister",
      "credit_id": "6109894e255dba002de4620e",
      "order": 18
    },
    {
      "adult": false,
      "gender": 2,
      "id": 2411333,
      "known_for_department": "Acting",
      "name": "Seun Shote",
      "original_name": "Seun Shote",
      "popularity": 0.952,
      "profile_path": "/33szNjKtUsTxlwV039Gec2PKQS2.jpg",
      "cast_id": 226,
      "character": "Arrakeen Residency Gardener",
      "credit_id": "617019e6a097dc00920af978",
      "order": 19
    },
    {
      "adult": false,
      "gender": 2,
      "id": 178629,
      "known_for_department": "Acting",
      "name": "Neil Bell",
      "original_name": "Neil Bell",
      "popularity": 3.347,
      "profile_path": "/pidZ4zM5KyGv35ErckTKYqReJDZ.jpg",
      "cast_id": 227,
      "character": "Sardaukar Bashar",
      "credit_id": "617019e6a097dc0065e51a15",
      "order": 20
    },
    {
      "adult": false,
      "gender": 0,
      "id": 1638835,
      "known_for_department": "Acting",
      "name": "Oliver Ryan",
      "original_name": "Oliver Ryan",
      "popularity": 2.69,
      "profile_path": "/S0YPiYOSikfqjR6HMuxoFDzh0f.jpg",
      "cast_id": 165,
      "character": "Hawat Specialist",
      "credit_id": "5e446b483dd12600165a37d1",
      "order": 21
    },
    {
      "adult": false,
      "gender": 2,
      "id": 1929092,
      "known_for_department": "Acting",
      "name": "Stephen Collins",
      "original_name": "Stephen Collins",
      "popularity": 0.6,
      "profile_path": "/wKI02sI9KHaPMBHjY0SKpLI6yen.jpg",
      "cast_id": 166,
      "character": "Harkonnen Trooper",
      "credit_id": "5e446b99596a91001301aefc",
      "order": 22
    },
    {
      "adult": false,
      "gender": 2,
      "id": 1083177,
      "known_for_department": "Acting",
      "name": "Charlie Rawes",
      "original_name": "Charlie Rawes",
      "popularity": 6.563,
      "profile_path": "/zsARROMEHNANOAI8wntYcn3BpOM.jpg",
      "cast_id": 162,
      "character": "Harkonnen Trooper",
      "credit_id": "5e446a8a41465c001ad29ace",
      "order": 23
    },
    {
      "adult": false,
      "gender": 2,
      "id": 3275311,
      "known_for_department": "Acting",
      "name": "Richard Carter",
      "original_name": "Richard Carter",
      "popularity": 0.694,
      "profile_path": "/vwMG8213y9UiCDXBPIUwzhVxUcX.jpg",
      "cast_id": 225,
      "character": "Harkonnen Trooper",
      "credit_id": "616d8946ba131b008e16d46f",
      "order": 24
    },
    {
      "adult": false,
      "gender": 2,
      "id": 1269682,
      "known_for_department": "Acting",
      "name": "Benjamin Dilloway",
      "original_name": "Benjamin Dilloway",
      "popularity": 2.079,
      "profile_path": "/reXJcitDu5hsCO7Hlra2ZFzr6Nn.jpg",
      "cast_id": 228,
      "character": "Sardaukar Assassin",
      "credit_id": "617019e6d4b9d9008a7b018e",
      "order": 25
    },
    {
      "adult": false,
      "gender": 2,
      "id": 3063993,
      "known_for_department": "Acting",
      "name": "Elmi Rashid Elmi",
      "original_name": "Elmi Rashid Elmi",
      "popularity": 1.144,
      "profile_path": "/kMH7mX7rzVrrPuWL0qVeYExXVcx.jpg",
      "cast_id": 207,
      "character": "Shamir",
      "credit_id": "610988955541fa005d8e28cf",
      "order": 26
    },
    {
      "adult": false,
      "gender": 2,
      "id": 1466868,
      "known_for_department": "Acting",
      "name": "Tachia Newall",
      "original_name": "Tachia Newall",
      "popularity": 0.784,
      "profile_path": "/ywvojfXK3uzw0IgVEVg3j00GPuy.jpg",
      "cast_id": 229,
      "character": "Tanat",
      "credit_id": "617019e6d4b9d9008a7b0191",
      "order": 27
    },
    {
      "adult": false,
      "gender": 1,
      "id": 1982903,
      "known_for_department": "Acting",
      "name": "Gloria Obianyo",
      "original_name": "Gloria Obianyo",
      "popularity": 2.681,
      "profile_path": "/8vRsNhtxFzYsHQItIKwcMW9flts.jpg",
      "cast_id": 158,
      "character": "Female Fremen",
      "credit_id": "5e35cc0c4ca676001a513c4a",
      "order": 28
    },
    {
      "adult": false,
      "gender": 2,
      "id": 2160722,
      "known_for_department": "Acting",
      "name": "Fehinti Balogun",
      "original_name": "Fehinti Balogun",
      "popularity": 1.176,
      "profile_path": "/lgwljS8zU7KWRlXMdyow34O7kvJ.jpg",
      "cast_id": 277,
      "character": "Male Fremen",
      "credit_id": "6195ce78fc5f060046a85373",
      "order": 29
    },
    {
      "adult": false,
      "gender": 1,
      "id": 3314410,
      "known_for_department": "Acting",
      "name": "Dora Kápolnai-Schvab",
      "original_name": "Dora Kápolnai-Schvab",
      "popularity": 0.6,
      "profile_path": "/rqmxqILAmCqIXCedRBtgh6NLaw2.jpg",
      "cast_id": 278,
      "character": "Baron Servant",
      "credit_id": "6195ceb071458f006186945b",
      "order": 30
    },
    {
      "adult": false,
      "gender": 1,
      "id": 3314411,
      "known_for_department": "Acting",
      "name": "Joelle",
      "original_name": "Joelle",
      "popularity": 2.444,
      "profile_path": "/rqmxqILAmCqIXCedRBtgh6NLaw2.jpg",
      "cast_id": 279,
      "character": "Baron Servant",
      "credit_id": "6195ceea29733800430b2097",
      "order": 31
    },
    {
      "adult": false,
      "gender": 2,
      "id": 2158768,
      "known_for_department": "Acting",
      "name": "Jimmy Walker",
      "original_name": "Jimmy Walker",
      "popularity": 1.4,
      "profile_path": "/2YZA7E7aIf8EjyZ6PUIk67U2glW.jpg",
      "cast_id": 280,
      "character": "Atreides Lieutenant",
      "credit_id": "6195cf1ce16e5a008ca8be81",
      "order": 32
    },
    {
      "adult": false,
      "gender": 0,
      "id": 1488465,
      "known_for_department": "Acting",
      "name": "Paul Bullion",
      "original_name": "Paul Bullion",
      "popularity": 4.63,
      "profile_path": "/uR76mlAgEpmj0WNnzJ7jG337fZF.jpg",
      "cast_id": 161,
      "character": "Sardaukar Soldier",
      "credit_id": "5e446a680c2710001a84e594",
      "order": 33
    },
    {
      "adult": false,
      "gender": 1,
      "id": 3314417,
      "known_for_department": "Acting",
      "name": "Milena Sidorova",
      "original_name": "Milena Sidorova",
      "popularity": 0.6,
      "profile_path": "/9kLGHnnFqCDFBZ1M048zLp4KIGh.jpg",
      "cast_id": 281,
      "character": "Human Spider Proxy",
      "credit_id": "6195d037e16e5a002b4ecb65",
      "order": 34
    },
    {
      "adult": false,
      "gender": 0,
      "id": 2059373,
      "known_for_department": "Acting",
      "name": "János Timkó",
      "original_name": "János Timkó",
      "popularity": 1.214,
      "profile_path": "/qHKNILSJE41Mtj2NUO6mdT29BeG.jpg",
      "cast_id": 282,
      "character": "Harkonnen Guard",
      "credit_id": "6195d078e16e5a0044d5d7aa",
      "order": 35
    },
    {
      "adult": false,
      "gender": 1,
      "id": 59051,
      "known_for_department": "Acting",
      "name": "Jean Gilpin",
      "original_name": "Jean Gilpin",
      "popularity": 2.005,
      "profile_path": "/8NRvEevVGpG0y5gSb7SvBMiUfur.jpg",
      "cast_id": 283,
      "character": "Bene Gesserit Ancestor (voice)",
      "credit_id": "6195d0abae3843006171c145",
      "order": 36
    },
    {
      "adult": false,
      "gender": 1,
      "id": 19995,
      "known_for_department": "Acting",
      "name": "Marianne Faithfull",
      "original_name": "Marianne Faithfull",
      "popularity": 4.717,
      "profile_path": "/dUubdaEhMHx5UFZnRnuI75Zs3W4.jpg",
      "cast_id": 284,
      "character": "Bene Gesserit Ancestor (voice)",
      "credit_id": "6195d0b9528b2e008b2e9ed6",
      "order": 37
    },
    {
      "adult": false,
      "gender": 1,
      "id": 53934,
      "known_for_department": "Acting",
      "name": "Ellen Dubin",
      "original_name": "Ellen Dubin",
      "popularity": 4.258,
      "profile_path": "/6pskknCFA9ELimcXdR5LMJb1JJn.jpg",
      "cast_id": 285,
      "character": "Bene Gesserit Ancestor (voice)",
      "credit_id": "6195d0c69512e1002afe9ce1",
      "order": 38
    }
  ];
}
